[build-system]
requires = ["setuptools>=69.0.2"]
build-backend = "setuptools.build_meta"

[project]
name = "schooner_dice"
version = "0.0.1"
authors = [
    { name="Chris Toth", email="toth.j.chris@gmail.com" },
]
description = "Modules for a dice game"
readme = "README.md"